### PR TITLE
ran swift 3.0 Xcode update script on tests

### PR DESCRIPTION
**Pull request by randallli**

### CODE REVIEW

**Review by ajsecord — CHANGES_REQUESTED** [review]
Can you please update .travis.yml to use Xcode 8.2 instead of 7?  https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions

**Comment by randallli** [comment]
Done. PTAL

**Review by ajsecord — APPROVED** [review]

**Review by ajsecord — CHANGES_REQUESTED** [review]
In .travis.yml, s/iphonesimulator9.3/iphonesimulator10.1/

**Comment by randallli** [comment]
looks like travis is working now. PTAL

**Review by ajsecord — APPROVED** [review]

**Pull request merged**
